#%RAML 1.0 DataType

displayName: Employee Details
description: These are the fields for Employee

type: object
properties:
  empid: string 
  firstname: string
  middlename: string
  lastname: string
  address1: string
  address2: string
  phone: number
  deptid: string
  designation: string
  dateofjoining: string
  salary: number
  previousemployer: string
