#%RAML 1.0 NamedExample

- empid: EMPID1303
  firstname: Ankit
  middlename: Dhananjay
  lastname: Khedlekar
  address1: Manikbaug, Sinhgad Road, Pune
  address2: India
  phone: 1234567890
  deptid: DEPTID1503
  designation: Developer
  dateofjoining: 01-Jan-22
  salary: 10000
  previousemployer: Blancco

- empid: EMPID1203
  firstname: Mohit
  middlename: Dhananjay
  lastname: Khedlekar
  address1: Manikbaug, Sinhgad Road, Pune
  address2: India
  phone: 1234567890
  deptid: DEPTID1501
  designation: Tester
  dateofjoining: 10-Jan-22
  salary: 6000
  previousemployer: Fresher